project_id = "ndmelhwkpthvgjiqarrs"

[functions.queimadas-live]
verify_jwt = false

[functions.process-unifilar-diagram]
verify_jwt = true

[functions.queimadas-archive]
verify_jwt = false

[functions.line-upload]
verify_jwt = true

[functions.import-lipower-dataset]
verify_jwt = true

[functions.geo-api]
verify_jwt = true

[functions.process-tower-asset]
verify_jwt = true

[functions.process-span-analysis]
verify_jwt = true

[functions.process-evento]
verify_jwt = true

[functions.process-dem-surface]
verify_jwt = true