project_id = "ndmelhwkpthvgjiqarrs"

[functions.queimadas-live]
verify_jwt = false

[functions.queimadas-archive]
verify_jwt = false

[functions.queimadas-footprints]
verify_jwt = false

[functions.get-weather-data]
verify_jwt = false

[functions.process-raster]
verify_jwt = true

[functions.detect-changes]
verify_jwt = true

[functions.evaluate-alerts]
verify_jwt = true

[functions.process-unifilar-diagram]
verify_jwt = true

[functions.line-upload]
verify_jwt = true

[functions.import-lipower-dataset]
verify_jwt = true

[functions.geo-api]
verify_jwt = true

[functions.process-tower-asset]
verify_jwt = true

[functions.process-span-analysis]
verify_jwt = true

[functions.process-evento]
verify_jwt = true

[functions.process-dem-surface]
verify_jwt = true